from pathlib import Path

path = Path("Assets/Rokas/Scripts/Core/GameSession.cs")
text = path.read_text(encoding="utf-8")
old = '''            LiveMessages = new LiveMessengerService(state, Messages);\n            LiveMessages.Changed += NotifyChanged;\n'''
new = '''            LiveMessages = new LiveMessengerService(state, Messages);\n'''
if old not in text:
    raise SystemExit("Expected LiveMessages Changed subscription was not present after core patch")
path.write_text(text.replace(old, new, 1), encoding="utf-8")
print("Preserved existing GameSession.Changed notification cardinality")

contract_path = Path("Tests/Core/ContractAttachmentActionTests.cs")
contract = contract_path.read_text(encoding="utf-8")
old_assert = '''                Equal(2, restored.Messages.GetConversation("guild").entries.Count, "offer plus accepted follow-up remain exactly once");\n                Equal(2, restored.Messages.GetConversation("yumiko").entries.Count,\n                    "Yumiko recommendation and one-time gift survive reload exactly once");\n'''
new_assert = '''                ConversationState restoredGuild = restored.Messages.GetConversation("guild");\n                Equal(3, restoredGuild.entries.Count,\n                    "offer and accepted follow-up remain exactly once while pending live acceptance context recovers once");\n                Equal(1, CountEventPrefix(restoredGuild, "guild-contract-test"),\n                    "original Guild contract offer identity remains exactly once after live recovery");\n                Equal(1, CountEventPrefix(restoredGuild, "guild-contract-accepted:"),\n                    "original Guild acceptance follow-up remains exactly once after live recovery");\n                Equal(1, CountEventPrefix(restoredGuild, "live:guild:accepted:"),\n                    "pending live acceptance continuation resolves exactly once after reload");\n                Equal(2, restored.Messages.GetConversation("yumiko").entries.Count,\n                    "Yumiko recommendation and one-time gift survive reload exactly once");\n'''
if old_assert not in contract:
    raise SystemExit("Expected ContractAttachmentActionTests save/load assertion anchor was not found")
contract = contract.replace(old_assert, new_assert, 1)
helper_anchor = '''        private static void Equal<T>(T expected, T actual, string message)\n        {\n'''
helper = '''        private static int CountEventPrefix(ConversationState conversation, string prefix)\n        {\n            int count = 0;\n            if (conversation == null || conversation.entries == null) return count;\n            for (int index = 0; index < conversation.entries.Count; index++)\n            {\n                MessageEntry entry = conversation.entries[index];\n                if (entry != null && (entry.eventId ?? string.Empty).StartsWith(prefix, StringComparison.Ordinal)) count++;\n            }\n            return count;\n        }\n\n        private static void Equal<T>(T expected, T actual, string message)\n        {\n'''
if helper_anchor not in contract:
    raise SystemExit("Expected ContractAttachmentActionTests helper anchor was not found")
contract_path.write_text(contract.replace(helper_anchor, helper, 1), encoding="utf-8")
print("Updated stale contract reload count while preserving exactly-once event checks")

message_events_path = Path("Tests/Core/GameSessionMessageEventTests.cs")
events = message_events_path.read_text(encoding="utf-8")
old_reload = '''                Equal(1, guild.entries.Count, "reload must preserve one completion event without redelivery");\n                Equal(expectedEventId, guild.entries[0].eventId, "reload must preserve deterministic event identity");\n                Equal("Контракт закрыт. Награда перечислена. Выполнение №1.", guild.entries[0].text,\n                    "reload must preserve authored completion context");\n                Equal(1, guild.unreadCount, "unread completion state must survive reload");\n                Equal(1, restored.Messages.TotalUnread, "total unread must survive reload");\n\n                Equal(false, restored.ClaimPayment(), "restored completed run cannot process payment again");\n                Equal(1, guild.entries.Count, "post-load repeated processing must not duplicate the event");\n                Equal(1, guild.unreadCount, "post-load repeated processing must not increment unread");\n'''
new_reload = '''                Equal(1, CountEventPrefix(guild, expectedEventId),\n                    "reload must preserve the core completion event exactly once without redelivery");\n                Equal(1, CountEventPrefix(guild, "live:guild:completed:"),\n                    "pending authored completion continuation must recover exactly once");\n                MessageEntry completion = FindEvent(guild, expectedEventId);\n                True(completion != null, "reload must preserve deterministic completion identity");\n                Equal("Контракт закрыт. Награда перечислена. Выполнение №1.", completion.text,\n                    "reload must preserve authored completion context");\n                int historyAfterRecovery = guild.entries.Count;\n                int unreadAfterRecovery = guild.unreadCount;\n                True(unreadAfterRecovery >= 1, "completion chain must remain unread after reload");\n                Equal(unreadAfterRecovery, restored.Messages.TotalUnread,\n                    "total unread must reflect the recovered Guild completion chain");\n\n                Equal(false, restored.ClaimPayment(), "restored completed run cannot process payment again");\n                Equal(historyAfterRecovery, guild.entries.Count, "post-load repeated processing must not duplicate history");\n                Equal(unreadAfterRecovery, guild.unreadCount, "post-load repeated processing must not increment unread");\n                Equal(1, CountEventPrefix(guild, expectedEventId),\n                    "post-load repeated processing must keep core completion exactly once");\n'''
if old_reload not in events:
    raise SystemExit("Expected GameSessionMessageEventTests reload assertion anchor was not found")
events = events.replace(old_reload, new_reload, 1)
old_repeat = '''            Equal(3, guild.entries.Count, "three genuine runs must create exactly three completion events");\n            for (int index = 0; index < 3; index++)\n            {\n                int run = index + 1;\n                MessageEntry entry = guild.entries[index];\n                Equal("guild-contract-completed:contract_subway_001:" + run, entry.eventId,\n                    "repeat-run event IDs must retain contract and completedRuns identity");\n                Equal("Контракт закрыт. Награда перечислена. Выполнение №" + run + ".", entry.text,\n                    "legitimate repeat runs must not render as indistinguishable completion spam");\n            }\n            Equal(3, session.State.completedRuns, "three genuine payments must advance completedRuns exactly three times");\n            Equal(3, guild.unreadCount, "each genuine new run remains one legitimate unread event");\n'''
new_repeat = '''            Equal(3, CountEventPrefix(guild, "guild-contract-completed:"),\n                "three genuine runs must create exactly three core completion events even with live continuations");\n            for (int index = 0; index < 3; index++)\n            {\n                int run = index + 1;\n                string eventId = "guild-contract-completed:contract_subway_001:" + run;\n                MessageEntry entry = FindEvent(guild, eventId);\n                True(entry != null, "repeat-run event ID must remain present: " + eventId);\n                Equal("Контракт закрыт. Награда перечислена. Выполнение №" + run + ".", entry.text,\n                    "legitimate repeat runs must retain their distinct authored completion context");\n            }\n            Equal(3, session.State.completedRuns, "three genuine payments must advance completedRuns exactly three times");\n            True(guild.unreadCount >= 3,\n                "each genuine core completion must remain represented in unread state even when live follow-ups also exist");\n'''
if old_repeat not in events:
    raise SystemExit("Expected GameSessionMessageEventTests repeat-run assertion anchor was not found")
events = events.replace(old_repeat, new_repeat, 1)
events_helper_anchor = '''        private static void True(bool actual, string message)\n        {\n'''
events_helpers = '''        private static MessageEntry FindEvent(ConversationState conversation, string eventId)\n        {\n            if (conversation == null || conversation.entries == null) return null;\n            for (int index = 0; index < conversation.entries.Count; index++)\n            {\n                MessageEntry entry = conversation.entries[index];\n                if (entry != null && string.Equals(entry.eventId, eventId, StringComparison.Ordinal)) return entry;\n            }\n            return null;\n        }\n\n        private static int CountEventPrefix(ConversationState conversation, string prefix)\n        {\n            int count = 0;\n            if (conversation == null || conversation.entries == null) return count;\n            for (int index = 0; index < conversation.entries.Count; index++)\n            {\n                MessageEntry entry = conversation.entries[index];\n                if (entry != null && (entry.eventId ?? string.Empty).StartsWith(prefix, StringComparison.Ordinal)) count++;\n            }\n            return count;\n        }\n\n        private static void True(bool actual, string message)\n        {\n'''
if events_helper_anchor not in events:
    raise SystemExit("Expected GameSessionMessageEventTests helper anchor was not found")
message_events_path.write_text(events.replace(events_helper_anchor, events_helpers, 1), encoding="utf-8")
print("Updated completion tests to verify core and live event identities independently")
